#!/usr/bin/env bash
#
# steamls 1.1 (2024-12-04)
#
# Copyright (c) 2024 Xezal O.
# Licensed under the MIT license, full text of which is available at https://github.com/pyroghetti/steamls/blob/main/LICENSE

IFS=$'\n'
LC_ALL=C.UTF-8
steamLib="${HOME}/.local/share/Steam/steamapps"
hideProton=1
hideRedist=1
hideRuntimes=1

steamlshelp()
{
	printf "steamls is a Bash script that lists installed Steam games and their AppIDs.\n"
	printf "Usage: steamls [-rps][-d DIR | -f]\n\n"
	printf " -h\tprint help and exit\n\n"
	printf "HIDDEN TOOLS\n\n"
	printf " -p\tunhide Proton\n"
	printf " -r\tunhide Steamworks Common Redistributables\n"
	printf " -s\tunhide Steam Linux Runtime\n\n"
	printf "DIRECTORY\n\n"
	printf " -d DIR provide an alternative Steam library path, omitting \"./steamapps\"\n"
	printf " -f\tsearches for Steam libraries in mounted devices and your home\n\tnote: only the first match will be taken to account\n\n"
	printf " Report bugs and suggest features at https://github.com/pyroghetti/steamls/issues\n or by emailing me at pyroghetti@protonmail.com\n"
	exit 0
}

while getopts ":hprsd:f" opts
do
	case "${opts}" in
		h) steamlshelp
			;;
		p) hideProton=0
			;;
		r) hideRedist=0
			;;
		s) hideRuntimes=0
			;;
		d) steamLib="${OPTARG}/steamapps"
			;;
		f) steamLib=$(find 2>&- "/run/media/${USER}" /mnt "${HOME}" -type d ! -empty ! -path "*compatdata/*/pfx*" -name "steamapps" -print -quit)

			if [ -z "${steamLib}" ];
			then printf "Steam library not found :/\n" && exit 1;
			else printf "Steam library found at ${steamLib}:\n\n";
			fi
			;;
		*) printf "Unrecognized flag or bad usage. Try steamls -h.\n" && exit 1
	esac
done

# Want to hide games? Run something like grepenv="keyword|appid|" steamls.
# E.g you can hide Half-Life 1 & 2 by either running grepenv="70|220|" steamls or grepenv="Half-Life|" steamls.
# Quotes are mandatory to prevent unintended pipeline behavior.

if [ "${hideProton}" = "1" ];
then grepenv="${grepenv}858280|961940|1054830|1113280|1245040|1420170|1493710|1580130|1887720|2180100|2230260|2348590|2805730|1161040|1826330|";
fi

if [ "${hideRedist}" = "1" ];
then grepenv="${grepenv}228980|";
fi

if [ "${hideRuntimes}" = "1" ];
then grepenv="${grepenv}1070560|1391110|1628350";
fi

[ ! -d "${steamLib}" ] && printf "${steamLib} doesn't exist or can't be read by ${USER}.\n" && exit 1

for appmanifest in "${steamLib}"/appmanifest_*.acf
do
	printf "%s = %s\n" \
		$(grep 2>&- '"appid"' "${appmanifest}" | cut --delimiter \" --fields=4) \
		$(grep 2>&- '"name"' "${appmanifest}" | cut --delimiter \" --fields=4)
		done |
		sort --general-numeric-sort |
		grep --extended-regexp --invert-match "^(${grepenv}) ="
